[package]
name = "backend"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
actix-web = "4.11.0"
include_dir = "0.7.4"
mime_guess = "2.0.5"
webbrowser = "1.0.5"
tokio = { version = "1.47.1", features = ["full"] }
actix-multipart = "0.7.2"
futures-util = "0.3.31"
umya-spreadsheet = "2.3.3"
serde = "1.0.226"
serde_json = "1.0.145"
structopt = "0.3.26"
structopt-derive = "0.4.18"
env_logger = "0.11.8"
log = "0.4.28"
uuid = { version = "1.18.1", features = ["v4"] }
genpdf = { version = "0.2", features = ["images"] }
num-format = "0.4.4"
chrono = "0.4.42"
actix-files = "0.6.8"
lettre = "0.11.18"
regex = "1.11.3"

[build-dependencies]
fs_extra = "1.3.0"

